{
 "title": "2527-v3-service-status-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (ingress) (\n  kube_ingress_info{namespace=\"infra\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_ingress_path{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (endpoint, namespace) (\n  kube_endpoint_address{namespace=\"infra\", ready=\"true\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_owner{\n  namespace=\"infra\",\n  owner_is_controller=\"true\",\n  owner_kind=\"ReplicaSet\"\n}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_ready{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"infra\",\n    cpu=\"total\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{namespace=\"infra\"}\n) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas_ready{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=\"infra\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() - kube_deployment_created{namespace=\"infra\"}) / 3600",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_deployment_status_replicas{namespace=\"infra\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}