prom/node-exporter:v1.8.2 node-exporter-v1.8.2
docker.elastic.co/beats/filebeat-oss:8.12.2 filebeat-oss-8.12.2
nginxinc/nginx-unprivileged:1.27.3-alpine3.20 nginx-unprivileged-1.27.3-alpine3.20
nginxinc/nginx-unprivileged:1.27.5-alpine3.21 nginx-unprivileged-1.27.5-alpine3.21
postgres:13-alpine postgres-13-alpine
postgres:14-alpine postgres-14-alpine
postgres:15-alpine postgres-15-alpine
postgres:16-alpine postgres-16-alpine
postgres:17-alpine postgres-17-alpine
redis:6-alpine redis-6-alpine
postgis/postgis:14-3.2 postgis-14-3.2
postgis/postgis:14-3.3 postgis-14-3.3
postgis/postgis:14-3.4 postgis-14-3.4
postgis/postgis:14-3.5 postgis-14-3.5
stakater/reloader:v1.4.8 reloader-1.4.8
