nginxinc/nginx-unprivileged:1.27.3-alpine3.20 nginx-unprivileged-1.27.3-alpine3.20
nginxinc/nginx-unprivileged:1.27.5-alpine3.21 nginx-unprivileged-1.27.5-alpine3.21
postgres:13-alpine postgres-13-alpine
postgres:14-alpine postgres-14-alpine
postgres:15-alpine postgres-15-alpine
postgres:16-alpine postgres-16-alpine
postgres:17-alpine postgres-17-alpine
redis:6-alpine redis-6-alpine
