airbyte/connector-builder-server:1.5.1 airbyte-connector-builder-server-1.5.1
airbyte/cron:1.5.1 airbyte-cron-1.5.1
airbyte/server:1.5.1 airbyte-server-1.5.1
airbyte/webapp:1.5.1  airbyte-webapp-1.5.1
airbyte/worker:1.5.1 airbyte-worker-1.5.1
airbyte/workload-api-server:1.5.1 airbyte-workload-api-server-1.5.1
airbyte/workload-launcher:1.5.1 airbyte-workload-launcher-1.5.1
alpine:3.20.1 alpine-3.20.1
grafana/grafana:11.1.5 grafana-11.1.5
mendhak/http-https-echo:31 mendhak-http-https-echo-31
nginxinc/nginx-unprivileged:1.27.3-alpine3.20 nginx-unprivileged:1.27.3-alpine3.20
nginx:latest nginx-latest
postgis/postgis:14-3.2 postgis-14-3.3
postgis/postgis:14-3.3 postgis-14-3.4
postgis/postgis:14-3.4 postgis-14-3.5
postgres:13-alpine postgres-13-alpine
postgres:14-alpine postgres-14-alpine
postgres:16-alpine postgres-16-alpine
redis:6-alpine redis-6-alpine
prom/alertmanager:v0.27.0 prom-alertmanager-v0.27.0
prom/prometheus:v2.54.1 prom-prometheus-v2.54.1
sqlpad/sqlpad:6.11.4 sqlpad-sqlpad-6.11.4
stakater/reloader:v1.0.69 stakater-reloader-v1.0.69
temporalio/auto-setup:1.26 temporalio-auto-setup-1.26
