 {{ define "slack.devops.text" }}
      {{range .Alerts}}{{.Annotations.DESCRIPTION}}
      {{end}}
{{ end }}

{{ define "slack.alert.text" }}
  {{ range .Alerts }}
    *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
    {{ if eq .Status "firing" -}}
    *Description:* {{ .Annotations.description }}
    {{- else -}}
    *Description:* Alert cleared
    {{- end }}
    *Details:*
    {{ range .Labels.SortedPairs }} - *{{ .Name }}:* `{{ .Value }}`
    {{ end }}
  {{ end }}
{{ end }}

{{ define "slack.alert.title" }}
  {{ with index .Alerts 0 }}
    {{ .Annotations.summary }}
  {{ end }}
{{ end }}
