{
 "title": "2527-v8-service-status-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"aks-apps1-.*\", namespace!=\"default\", namespace!=\"kube-system\", namespace!=\"gatekeeper-system\", namespace!=\"monitoring\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_service_info{namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Health",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  kube_pod_status_ready{\n    namespace=\"default\",\n    condition=\"true\"\n  }\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NGINX Controller – Requests (total)",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nginx- traffic received?",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by (namespace, ingress, service) (\n  rate(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\"\n    }[5m]\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Per-Ingress Traffic",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (namespace, ingress, service, host)(\n  rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[5m])\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress HTTP status codes",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "sum by (namespace, ingress, service, status)(\n  rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[5m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress Latency",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, namespace, ingress, service)(\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\"}[5m])\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingresses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress Health",
     "type": "table",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum by (namespace, service) (\n  kube_endpoint_address{namespace=~\"$namespace\", ready=\"true\"}\n)\nor\nsum by (namespace, service) (\n  kube_service_info{namespace=~\"$namespace\"} * 0\n)\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress - Defined Rules",
     "type": "table",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "kube_ingress_path{namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress to Service Mapping",
     "type": "table",
     "gridPos": { "h": 3, "w": 22, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "kube_ingress_info{namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "kube_service_info{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service endpoints",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 3 },
   "targets": [
    {
     "expr": "sum by (namespace, service) (\n  kube_endpoint_address{namespace=\"$namespace\", ready=\"true\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (\n  kube_deployment_spec_replicas{namespace=\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, deployment) (\n  kube_deployment_status_replicas_available{namespace=\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, deployment) (\n  kube_deployment_status_replicas_available{namespace=\"$namespace\"}\n)\n-\nsum by (namespace, deployment) (\n  kube_deployment_spec_replicas{namespace=\"$namespace\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pods Not Ready",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{namespace=~\"$namespace\"}\n-\nkube_deployment_status_replicas_ready{namespace=~\"$namespace\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Ready",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 3, "y": 13 },
   "targets": [
    {
     "expr": "(\n  sum by (namespace, deployment) (\n    kube_deployment_status_replicas_ready\n{\n      namespace=~\"$namespace\"\n    }\n  )\n)\nor\non (namespace, deployment)\n(\n  kube_deployment_spec_replicas{\n      namespace=~\"$namespace\"\n  } * 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{\n  namespace=~\"$namespace\",\n  reason=~\"CrashLoopBackOff|ImagePullBackOff|ErrImagePull|CreateContainerConfigError|RunContainerError\"\n}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Images",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_pod_container_info{\n  namespace=~\"$namespace\"\n}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}