{
 "title": "service-status-dashboard-OVERALL",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_service_info{namespace!~\"$namespace_filter\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_service_info{namespace!~\"$namespace_filter\"},service)"
    }
   },
   {
    "name": "namespace_filter",
    "label": "namespace_filter",
    "query": "kube-.*|.*-system|monitoring|default"
   }
  ]
 },
 "panels": [
  { "title": "Service: $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\",\n      service=~\"$service\"\n    }[1h]\n  )\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful (non-5xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=\"infra\",\n      service=\"$service\",\n      status!~\"5..\"\n    }[1h]\n  )\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running pods ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_ready{\n    namespace=~\"$namespace\",\n    condition=\"true\",\n    pod=~\"^(${service:regex}).*\"\n  }\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed / missing pods",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_ready{\n    namespace=~\"$namespace\",\n    condition=\"false\",\n    pod=~\"^(${service:regex}).*\"\n  }\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarted pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_ready{\n    namespace=~\"$namespace\",\n    condition=\"false\",\n    pod=~\"^(${service:regex}).*\"\n  }\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU(cores)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\nsum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=~\"$namespace\",\n    pod=~\"$service.*\",\n    container!=\"\",\n    image!=\"\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem(GB)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    namespace=~\"$namespace\",\n    pod=~\"$service.*\",\n    container!=\"\",\n    image!=\"\"\n  }\n) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}