{
 "title": "service-status-dashboard-OVERALL",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_service_info,namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_service_info,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service: $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\",\n      service=~\"$service\"\n    }[1h]\n  )\n) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Successful (non-5xx)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=\"infra\",\n      service=\"$service\",\n      status!~\"5..\"\n    }[1h]\n  )\n) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running pods ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  kube_pod_status_phase{\n    namespace=\"infra\",\n    phase=\"Running\",\n    service=\"$service\"\n  }\n) or vector(0)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed / missing pods",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum(\n    kube_deployment_spec_replicas{\n      namespace=~\"$namespace\",\n      deployment=~\"^$service.*\"\n    }\n  )\n-\n  sum(\n    kube_deployment_status_replicas_ready{\n      namespace=~\"$namespace\",\n      deployment=~\"^$service.*\"\n    }\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Restarted pods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  increase(\n    kube_pod_container_status_restarts_total{\n      namespace=~\"$namespace\",\n      pod=~\"^$service.*\"\n    }[1h]\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}