{
 "title": "2527-v7-service-status-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Ingresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingresses defined",
   "type": "table",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_ingress_info{namespace=\"infra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Health",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (namespace, service) (\n  kube_endpoint_address{namespace=\"infra\", ready=\"true\"}\n)\nor\nsum by (namespace, service) (\n  kube_service_info{namespace=\"infra\"} * 0\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kube_service_info{namespace=\"infra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service endpoints",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "sum by (namespace, service) (\n  kube_endpoint_address_available{namespace=\"infra\"}\n)\nor on (namespace, service)\n(\n  kube_service_info{namespace=\"infra\"} * 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (namespace, deployment) (\n  kube_deployment_spec_replicas{namespace=\"infra\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, deployment) (\n  kube_deployment_status_replicas_available{namespace=\"infra\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Ready",
     "type": "table",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "(\n  sum by (namespace, deployment) (\n    kube_deployment_status_replicas_ready\n{\n      namespace=\"infra\"\n    }\n  )\n)\nor\non (namespace, deployment)\n(\n  kube_deployment_spec_replicas{\n    namespace=\"infra\"\n  } * 0\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods Not Ready",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{namespace=\"infra\"}\n-\nkube_deployment_status_replicas_ready{namespace=\"infra\"}\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failing pods",
     "type": "table",
     "gridPos": { "h": 5, "w": 21, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{\n  namespace=\"infra\",\n  reason=~\"CrashLoopBackOff|ImagePullBackOff|ErrImagePull|CreateContainerConfigError|RunContainerError\"\n}\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Images",
     "type": "table",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "kube_pod_container_info{\n  namespace=\"infra\"\n}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}