{
 "title": "2527-v8.11.0-service-status-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"aks-apps1-.*\", namespace!=\"default\", namespace!=\"kube-system\", namespace!=\"gatekeeper-system\", namespace!=\"monitoring\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_service_info{namespace=~\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nginx Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller Health (Number of ready pods)",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (\n  kube_pod_status_ready{\n    namespace=\"default\",\n    condition=\"true\"\n  }\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NGINX Controller – Requests/Sec (total)",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nginx- traffic received",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (namespace, ingress, service) (\n  rate(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\",\n      service=~\"$service\"\n    }[5m]\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Per-Ingress Traffic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (namespace, ingress, service, status, status_text, severity) (\n\n  label_replace(\n    label_replace(\n      rate(nginx_ingress_controller_requests{namespace=~\"$namespace\", service=~\"$service\", status=~\"5..\"}[5m]),\n      \"status_text\", \"SERVER ERROR\", \"status\", \".*\"\n    ),\n    \"severity\", \"1\", \"status\", \".*\"\n  )\n\n  or\n\n  label_replace(\n    label_replace(\n      rate(nginx_ingress_controller_requests{namespace=~\"$namespace\", service=~\"$service\",status=~\"4..\"}[5m]),\n      \"status_text\", \"CLIENT ERROR\", \"status\", \".*\"\n    ),\n    \"severity\", \"2\", \"status\", \".*\"\n  )\n\n  or\n\n  label_replace(\n    label_replace(\n      rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",service=~\"$service\", status=~\"3..\"}[5m]),\n      \"status_text\", \"REDIRECT\", \"status\", \".*\"\n    ),\n    \"severity\", \"3\", \"status\", \".*\"\n  )\n\n  or\n\n  label_replace(\n    label_replace(\n      rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",service=~\"$service\", status=~\"2..\"}[5m]),\n      \"status_text\", \"OK\", \"status\", \".*\"\n    ),\n    \"severity\", \"4\", \"status\", \".*\"\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress Latency",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, namespace, ingress, service)(\n    rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=~\"$namespace\", service=~\"$service\"}[5m])\n  )\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingresses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress Health",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (namespace, service) (\n  kube_endpoint_address{namespace=~\"$namespace\", service=~\"$service\", ready=\"true\"}\n)\nor\nsum by (namespace, service) (\n  kube_service_info{namespace=~\"$namespace\", service=~\"$service\"} * 0\n)\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress - Defined Rules",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kube_ingress_path{namespace=~\"$namespace\", service_name=~\"$service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ingress to Service Mapping",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "kube_ingress_info{namespace=~\"$namespace\",ingress=~\"^$service.*\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services",
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "kube_service_info{namespace=~\"$namespace\", service=~\"$service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service endpoints",
     "type": "table",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 52 },
     "targets": [
      {
       "expr": "(\n  count by (namespace, service) (\n    label_replace(\n      kube_endpoint_address{\n        namespace=~\"$namespace\",\n        endpoint=~\"$service\",\n        ready=\"true\"\n      },\n      \"service\", \"$1\",\n      \"endpoint\", \"(.*)\"\n    )\n  )\n)\nOR on (namespace, service)\n(\n  kube_service_info{\n    namespace=~\"$namespace\",\n    service=~\"$service\"\n  } * 0\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum by (namespace, deployment) (\n  kube_deployment_spec_replicas{namespace=~\"$namespace\", deployment=~\"$service\"}\n)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, deployment) (\n  kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$service\"}\n)\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (namespace, deployment) (\n  kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$service\"}\n)\n-\nsum by (namespace, deployment) (\n  kube_deployment_spec_replicas{namespace=~\"$namespace\", deployment=~\"$service\"}\n)\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Not Ready",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 133 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  kube_deployment_spec_replicas{namespace=\"$namespace\"}\n-\n  kube_deployment_status_replicas_ready{namespace=\"$namespace\"}\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods Ready",
     "type": "table",
     "gridPos": { "h": 4, "w": 21, "x": 3, "y": 133 },
     "targets": [
      {
       "expr": "(\n  sum by (namespace, deployment) (\n    kube_deployment_status_replicas_ready\n{\n      namespace=~\"$namespace\", deployment=~\"^$service.*\"\n    }\n  )\n)\nor\non (namespace, deployment)\n(\n  kube_deployment_spec_replicas{\n      namespace=~\"$namespace\", deployment=~\"^$service.*\"\n  } * 0\n)\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failing/Stuck pods",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{\n  namespace=~\"$namespace\",\n  reason=~\"ContainerCreating|CrashLoopBackOff|ImagePullBackOff|ErrImagePull|CreateContainerConfigError|RunContainerError\"\n}\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Images",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 142 },
     "targets": [
      {
       "expr": "kube_pod_container_info{\n  namespace=~\"$namespace\", pod=~\"^$service.*\"\n}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}