{
 "title": "Review apps",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "NAMESPACE",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\".*(review-|pr-).*\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Old pods per namespace over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(count((time() - kube_pod_created{pod=~\".*(review-|pr-).*\"}) / (60*60*24) > 7) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~\"$NAMESPACE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old deployments per namespace now",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(count((time() - kube_deployment_created{deployment=~\".*(review-|pr-).*\"}) / (60*60*24) > 7) by(namespace))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old deployments in namespace",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((time() - kube_deployment_created{namespace=~\"$NAMESPACE\", deployment=~\".*(review-|pr-).*\"}) / (60*60*24) > 7)\r\n",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Old pods in namespace",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 11, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((time() - kube_pod_created{namespace=~\"$NAMESPACE\", pod=~\".*(review-|pr-).*\"}) / (60*60*24) > 7)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}