{
 "title": "service-status-dashboard-overall",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace_filter",
    "label": "namespace_filter",
    "query": "kube-.*|.*-system|monitoring|default"
   },
   { "name": "service_filter", "label": "service_filter", "query": ".*(-review-|-pr-).*\n" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_service_info{namespace!~\"$namespace_filter\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(kube_service_info{namespace=~\"$namespace\", namespace!~\"$namespace_filter\", service!~\"$service_filter\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service: $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Failed Requests (4xx + 5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\",\n      service=~\"$service\",\n      status=~\"4..|5..\"\n    }[$__range]\n  )\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful (non-4xx|5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\",\n      service=~\"$service\",\n      status!~\"4..|5..\"\n    }[$__range]\n  )\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running pods ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_ready{\n    namespace=~\"$namespace\",\n    condition=\"true\",\n    pod=~\"^(${service:regex}).*\"\n  }\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed / missing pods",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_ready{\n    namespace=~\"$namespace\",\n    condition=\"false\",\n    pod=~\"^(${service:regex}).*\"\n  }\n) or vector(0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarted pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    kube_pod_container_status_restarts_total{\n      namespace=~\"$namespace\",\n      pod=~\"^(${service:regex}).*\"\n    }[$__range]\n  )\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % Util",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=~\"$namespace\",\n    pod=~\"$service.*\",\n    container!=\"\",\n    image!=\"\"\n  }[$__range])\n)\n/\nsum(\n  kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    pod=~\"$service.*\",\n    resource=\"cpu\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem % util",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  container_memory_working_set_bytes{\n    namespace=~\"$namespace\",\n    pod=~\"$service.*\",\n    container!=\"\",\n    image!=\"\"\n  }\n)\n/\nsum(\n  kube_pod_container_resource_limits{\n    namespace=~\"$namespace\",\n    pod=~\"$service.*\",\n    resource=\"memory\"\n  }\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}