name: Deploy Environment

inputs:
  azure_credentials:
    description: Credentials with Contributor & KeyVault access to Azure subscription
    required: true
  environment_name:
    description: Name of the environment in Makefile
    required: true

runs:
  using: composite

  steps:
  - name: Set environment variables
    run: |
      TERRAFORM_VERSION=$(awk '/{/{f=/^terraform/;next}f' terraform_aks_cluster/terraform.tf | grep -o [0-9\.]*)
      . config/${{ inputs.environment_name }}.sh

      if [ -z "$RESOURCE_GROUP_NAME" ]; then
        echo "::error ::RESOURCE_GROUP_NAME not defined in config shell script"
        exit 1
      fi

      if [ -z "$STORAGE_ACCOUNT_NAME" ]; then
        echo "::error ::STORAGE_ACCOUNT_NAME not defined in config shell script"
        exit 1
      fi

      if [ -z "$TERRAFORM_VERSION" ]; then
        echo "::error ::Failed to extract TERRAFORM_VERSION from terraform.tf"
        exit 1
      fi

      echo "resource_group_name=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV
      echo "storage_account_name=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
      echo "terraform_version=$TERRAFORM_VERSION" >> $GITHUB_ENV

      case ${{ inputs.environment_name }} in
        platform-test)
          APP_DOMAIN=platform-test.teacherservices.cloud
          ;;
        test)
          APP_DOMAIN=test.teacherservices.cloud
          FRONT_DOOR_TEST=https://staging.apply-for-teacher-training.service.gov.uk/check
          DATABASE_TEST=https://staging.apply-for-teacher-training.service.gov.uk/integrations/monitoring/all
          ;;
        production)
          APP_DOMAIN=teacherservices.cloud
          FRONT_DOOR_TEST=https://www.apply-for-teacher-training.service.gov.uk/check
          DATABASE_TEST=https://www.apply-for-teacher-training.service.gov.uk/integrations/monitoring/all
          ;;
      esac
      echo "APP_DOMAIN=$APP_DOMAIN" >> $GITHUB_ENV
      echo "FRONT_DOOR_TEST=$FRONT_DOOR_TEST" >> $GITHUB_ENV
      echo "DATABASE_TEST=$DATABASE_TEST" >> $GITHUB_ENV

    shell: bash
    working-directory: cluster

  - uses: Azure/login@v1
    with:
      creds: ${{ inputs.azure_credentials }}

  - id: deploy-arm-resources
    run: |
      make ci ${{ inputs.environment_name }} deploy-azure-resources
    shell: bash

  - uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ env.terraform_version }}
      terraform_wrapper: false

  - name: Set ARM and kubelogin environment
    uses: DFE-Digital/github-actions/set-kubelogin-environment@master
    with:
      azure-credentials: ${{ inputs.AZURE_CREDENTIALS }}

  - id: terraform
    run: |
      make ci ${{ inputs.environment_name }} terraform-apply
      cd cluster/terraform_aks_cluster
      TFOUTPUTS=$(terraform output --json)
      OUTPUTS=($(jq -r <<< "$TFOUTPUTS" | jq -r 'keys | @sh' | tr -d \'))
      for o in "${OUTPUTS[@]}"
      do
        echo ${o}=$(jq -r .${o}.value <<< "$TFOUTPUTS") >> $GITHUB_ENV
      done
    shell: bash

  - name: Install kubectl
    uses: azure/setup-kubectl@v4.0.0
    with:
      version: "v1.26.1" # default is latest stable

  - name: Smoke tests
    shell: bash
    run: |
      echo Check ingress...
      curl -sS --fail "https://aaa.${APP_DOMAIN}/healthz" > /dev/null

      echo Check welcome app...
      curl -sS --fail "https://www.${APP_DOMAIN}/" > /dev/null

      if [[ -n "$FRONT_DOOR_TEST" ]]; then
        echo Check Apply app via front door...
        curl -sS --fail "$FRONT_DOOR_TEST" > /dev/null
      fi

      if [[ -n "$DATABASE_TEST" ]]; then
        echo Check Apply database via healthcheck page...
        curl -sS --fail "$DATABASE_TEST" > /dev/null
      fi

      echo Get cluster credentials...
      make ci ${{ inputs.environment_name }} get-cluster-credentials

      echo Get namespaces...
      kubectl get namespaces | grep -q infra
