name: Validate Terraform

inputs:
  github_token:
    description: The GitHub access token
    required: true
  terraform_root_folder:
    description: The folder that contains the terraform to be validated
    required: true
  terraform_modules_tag:
    description: Tag of terraform-modules repository - main, testing or stable (optional)
    required: false
    default: ''
  terraform_modules_dir:
    description: Directory where terraform-modules repository is downloaded (optional)
    required: false
    default: ''

runs:
  using: composite

  steps:
  - run: |
      TERRAFORM_VERSION=$(awk '/{/{f=/^terraform/;next}f' terraform.tf | grep -o [0-9\.]*)

      if [ -z "$TERRAFORM_VERSION" ]; then
        echo "::error ::Failed to extract terraform_version from terraform.tf"
        exit 1
      fi

      echo "terraform_version=$TERRAFORM_VERSION" >> $GITHUB_ENV
    shell: bash
    working-directory: ${{ inputs.terraform_root_folder }}

  - uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ env.terraform_version }}

  - run: terraform fmt -check -diff
    shell: bash
    working-directory: ${{ inputs.terraform_root_folder }}

  - if: inputs.terraform_modules_tag != ''
    run: |
      git clone --depth=1 --single-branch --branch ${{ inputs.terraform_modules_tag }} https://github.com/DFE-Digital/terraform-modules.git vendor/modules/${{ inputs.terraform_modules_dir }}
    shell: bash
    working-directory: ${{ inputs.terraform_root_folder }}

  - run: |
      terraform init -backend=false
      terraform validate -no-color
    shell: bash
    working-directory: ${{ inputs.terraform_root_folder }}

  - uses: reviewdog/action-tflint@v1.17
    with:
      github_token: ${{ inputs.github_token }}
      tflint_rulesets: azurerm
      working_directory: ${{ inputs.terraform_root_folder }}
