global:
templates:
  - '/etc/alertmanager/*.tmpl'
route:
  receiver: alert-default
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 30m
  routes:
    - receiver: slack_demo
      match:
        severity: slack
      group_wait: 10s
      repeat_interval: 1m
receivers:
- name: alert-default
- name: slack_demo
  slack_configs:
  - api_url: '${slack_secret}'
    channel: '${slack_channel}'
    send_resolved: true
    text: '{{ template "slack.devops.text"  }}'
