apiVersion: 1
datasources:
- name: Thanos
  type: prometheus
  access: proxy
  url: http://thanos-querier.monitoring.svc.cluster.local:9090
  isDefault: true
  jsonData:
    timeInterval: "5s"
    httpMethod: GET
  editable: true
