name: Set maintenance mode

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
        - development
        - production
      mode:
        required: true
        type: choice
        options:
        - enable
        - disable

jobs:
  set-maintenance-mode:
    name: Set maintenance mode
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Enable or disable maintenance mode
      uses: DFE-Digital/github-actions/maintenance@master
      with:
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        environment: ${{ inputs.environment }}
        mode: ${{ inputs.mode }}
        docker-repository: #DOCKER_REPOSITORY#-maintenance
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Send notification to Teams
      run: |
        payload=$(jq -n \
        --arg repo "${{ github.repository }}" \
        --arg actor "${{ github.actor }}" \
        --arg env "${{ inputs.environment }}" \
        --arg mode "${{ inputs.mode }}" \
        --arg status "${{ job.status }}" \
        --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
        '{
          repository: $repo,
          actor: $actor,
          environment: $env,
          mode: $mode,
          status: $status,
          run_url: $url
        }')

        curl -X POST -H 'Content-Type: application/json' \
          -d "$payload" \
          "${{ secrets.TEAMS_WEBHOOK_URL }}"