CONFIG=development
CONFIG_SHORT=dv
AZ_SUBSCRIPTION=s189-teacher-services-cloud-development
RESOURCE_PREFIX=s189d01
ENV_TAG=Dev
RESOURCE_GROUP_NAME=${RESOURCE_PREFIX}-tsc-${CONFIG_SHORT}-rg
KEYVAULT_NAME=${RESOURCE_PREFIX}-tsc2-${CONFIG_SHORT}-kv
STORAGE_ACCOUNT_NAME=${RESOURCE_PREFIX}tsctfstate${CONFIG_SHORT}
