CONFIG=production
CONFIG_SHORT=pd
AZ_SUBSCRIPTION=s189-teacher-services-cloud-production
RESOURCE_PREFIX=s189p01
ENV_TAG=Prod
RESOURCE_GROUP_NAME=${RESOURCE_PREFIX}-tscdomains-rg
KEYVAULT_NAME=${RESOURCE_PREFIX}-tscdomains-kv
STORAGE_ACCOUNT_NAME=${RESOURCE_PREFIX}tscdomainstf
