apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculate-teacher-pay.education.gov.uk
spec:
  ingressClassName: nginx
  rules:
  - host: calculate-teacher-pay.education.gov.uk
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: calculate-teacher-pay-production
            port:
              number: 80
