name: Deploy Alerting

on:
  push:
    branches:
      - main
    paths:
      - 'alerting/**'
  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
      - reopened
      - opened
      - converted_to_draft
    paths:
      - 'alerting/**'

jobs:
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Validate alerting/terraform_logic_app
      uses: ./.github/actions/validate-terraform
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        terraform_root_folder: alerting/terraform_logic_app
        terraform_modules_tag: main

    - name: Validate alerting/terraform_action_group
      uses: ./.github/actions/validate-terraform
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        terraform_root_folder: alerting/terraform_action_groups
        terraform_modules_tag: main

    - name: Notify teams channel on job failure
      if: ${{ failure() && github.ref == 'refs/heads/main' }}
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: Deploy Alerting
        service: Teacher Services Cloud
        message: |
          terraform alerting validation failed

  deploy:
    name: Deploy Alerting
    if: github.ref == 'refs/heads/main'
    concurrency: deploy_${{ matrix.environment }}
    environment:
      name: ${{ matrix.environment }}
    needs: [validate-terraform]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment: [test]
    permissions:
      id-token: write # Required for OIDC authentication to Azure

    steps:
    - uses: actions/checkout@v6

    - uses: Azure/login@v3
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.terraform_version }}
        terraform_wrapper: false

    - id: terraform
      run: |
        make ci ${{ inputs.environment_name }} alerting-apply
        cd alerting/terraform
        TFOUTPUTS=$(terraform output --json)
        OUTPUTS=($(jq -r <<< "$TFOUTPUTS" | jq -r 'keys | @sh' | tr -d \'))
        for o in "${OUTPUTS[@]}"
        do
          echo ${o}=$(jq -r .${o}.value <<< "$TFOUTPUTS") >> $GITHUB_ENV
        done
      shell: bash

    - name: Notify teams channel on job failure
      if: ${{ failure() }}
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: Deploy Alerting
        service: Teacher Services Cloud
        message: |
          The cluster deployment to ${{ matrix.environment }} has failed

    - name: Notify teams channel on workflow success
      uses: DFE-Digital/github-actions/send-to-teams-channel@master
      with:
        teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: Deploy Alerting
        service: Teacher Services Cloud
        status: good
        minimal: true
        message: |
          A cluster deployment to ${{ matrix.environment }} has completed successfully
