name: Mirror DockerHub Images to GHCR

on:
    workflow_dispatch:
    schedule:
      - cron: "0 6 * * 0"  # Weekly on Sundays at 06:00 UTC
    push:
      branches:
        - 2366-spike-logging-workflow-runs

permissions:
  contents: read
  packages: write
  id-token: write



jobs:
    mirror:
        runs-on: ubuntu-latest
        environment: development
        env:
          MY_ENV: development
        steps:
          - name: SendToLogit - Workflow Started
            shell: bash
            run: |
              curl -i  \
                 -H "ApiKey: ${{ secrets.LOGIT_API_KEY }}" \
                 -H "Content-Type: application/json" \
                 -H "LogType: custom" \
                https://api-uk1.logit.io/v2 \
                -d '{
                "source": "message",
                "labels": {
                        "workflow-purpose": "deployment"
                },
                "log": {
                        "level": "info"
                },
                "host": {
                        "name": "github.com"
                },
                "logtype": "custom",
                "version": "1",
                "event": {
                        "category": "ci",
                        "type": "pipeline",
                        "action": "$${{ github.action}}",
                        "outcome": "${{ job.status }}"
                },
                "user": {
                        "name": "${{ github.actor }}"
                },
                "ci": {
                        "pipeline_id": "${{ github.run_id }}",
                        "job_name": "${{ github.job }}",
                        "workflow_name": "${{ github.workflow }}",
                        "execution_id": "${{ github.run_id }}"
                },
                "ecs": {
                        "version": "8.11.0"
                },
                "git": {
                        "branch": "${{ github.ref }}",
                        "commit": {
                                "id": "${{ github.sha }}",
                                "message": "${{ github.event.head_commit.message }}"
                        },
                        "repository": {
                                "name": "${{ github.repository }}"
                        }
                },
                "message": "Step started",
                "url": {
                  "original": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
               }'
            env:
              LOGIT-API-KEY: ${{secrets.LOGIT_API_KEY}}

          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: github-actions
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: fail step
            run: false

          - name: Mirror images from lookup file
            run: |
                echo "Pulling image nginxinc/nginx-unprivileged:1.27.3-alpine3.20"
                docker pull -q "nginxinc/nginx-unprivileged:1.27.3-alpine3.20"
                echo "Tagging nginxinc/nginx-unprivileged:1.27.3-alpine3.20 as ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"
                docker tag nginxinc/nginx-unprivileged:1.27.3-alpine3.20 ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20
                echo "Pushing ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"
                docker push -q "ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"

          - name: SendToLogit - Workflow Completed
            if: false
            shell: bash
            run: |
              curl -i  \
                 -H "ApiKey: ${{ secrets.LOGIT_API_KEY }}" \
                 -H "Content-Type: application/json" \
                 -H "LogType: custom" \
                https://api-uk1.logit.io/v2 \
                -d '{
                "source": "message",
                "target": "github",
                "logtype": "custom",
                "Version": "1",
                "event": {
                  "category": "ci"
                }'
            env:
              LOGIT-API-KEY: ${{secrets.LOGIT_API_KEY}}