name: Mirror DockerHub Images to GHCR

on:
    workflow_dispatch:
    schedule:
      - cron: "0 6 * * 0"  # Weekly on Sundays at 06:00 UTC
    push:
      branches:
        - 2366-spike-logging-workflow-runs

permissions:
  contents: read
  packages: write
  id-token: write



jobs:
    mirror:
        runs-on: ubuntu-latest
        environment: development
        steps:
          - name: SendToLogit - Workflow Started
            if: false
            uses: DFE-Digital/github-actions/SendToLogit@master
            with:
              LOGIT-API-KEY: ${{secrets.LOGIT_API_KEY}}
              JSON:   |
                      '{"Application": "${{ github.repository}}",
                      "Status":"Starting - ${{ job.status }}",
                      "Action": "${{ github.repository }}",
                      "Environment": "${{ env.environment }}",
                      "Version": "1" }'

          - name: Debug Logit API Key and JSON
            run: |
              echo "LOGIT_API_KEY starts with: ${LOGIT_API_KEY:0:5}"
            env:
              LOGIT_API_KEY: ${{ secrets.LOGIT_API_KEY }}

          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: github-actions
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Mirror images from lookup file
            run: |
                echo "Pulling image nginxinc/nginx-unprivileged:1.27.3-alpine3.20"
                docker pull -q "nginxinc/nginx-unprivileged:1.27.3-alpine3.20"
                echo "Tagging nginxinc/nginx-unprivileged:1.27.3-alpine3.20 as ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"
                docker tag nginxinc/nginx-unprivileged:1.27.3-alpine3.20 ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20
                echo "Pushing ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"
                docker push -q "ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"

          - name: SendToLogit - Workflow Completed
            uses: DFE-Digital/github-actions/SendToLogit@master
            with:
              LOGIT-API-KEY: ${{secrets.LOGIT_API_KEY}}
              JSON:   |
                      '{"Application": "${{ github.repository }}",
                      "Status": "Completed - ${{ job.status }}",
                      "Action": "${{ github.workflow }}",
                      "Environment": "${{ env.environment }}",
                      "Version": "1" }'