name: Mirror DockerHub Images to GHCR

on:
    workflow_dispatch:
    schedule:
      - cron: "0 6 * * 0"  # Weekly on Sundays at 06:00 UTC
    push:
      branches:
        - 2366-spike-logging-workflow-runs

permissions:
  contents: read
  packages: write
  id-token: write



jobs:
    mirror:
        runs-on: ubuntu-latest
        environment: development
        env:
          MY_ENV: development
        steps:

          - name: build base Logit json payload
            run: |
              cat > payload_base.json <<'JSON'
              {
                "labels": { "workflow-purpose": "deployment" },
                "host": { "name": "github.com" },
                "logtype": "custom",
                "event": {
                  "category": "ci",
                  "type": "pipeline",
                  "action": "${{ github.action }}",
                  "outcome": "${{ job.status }}"
                },
                "user": { "name": "${{ github.actor }}" },
                "ci": {
                  "pipeline_id": "${{ github.run_id }}",
                  "job_name": "${{ github.job }}",
                  "workflow_name": "${{ github.workflow }}",
                  "run_id": "${{ github.run_id }}"
                },
                "git": {
                  "branch": "${{ github.ref }}",
                  "commit": {
                    "id": "${{ github.sha }}",
                    "message": "${{ github.event.head_commit.message }}"
                  }
                },
                "repository": {
                  "name": "${{ github.repository }}"
                }
              }
              JSON

          - name: SendToLogit - Workflow Started
            shell: bash
            env:
              STEP_NAME: "WorkflowStarted"
              LOGIT_API_KEY: ${{secrets.LOGIT_API_KEY}}
              URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            run: |
              jq -s \
                --arg step_timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
                --arg step_name "${STEP_NAME}" \
                --arg url "${URL}" \
                --arg status "${{ job.status }}" '
                .[0] * {
                 "@timestamp": $step_timestamp,
                 "message": $step_name,
                 "url": {
                   "original": $url
                  },
                 "event": {
                    "outcome": $status,
                    "action": $step_name
                  }
                }' payload_base.json > payload.json

              curl -i  \
                 -H "Authorization: ApiKey $LOGIT_API_KEY" \
                 -H "Content-Type: application/json" \
                 -H "LogType: custom" \
                 --data-binary @payload.json \
                 https://api-uk1.logit.io/v2



          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to GHCR
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: github-actions
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Mirror images from lookup file
            run: |
                echo "Pulling image nginxinc/nginx-unprivileged:1.27.3-alpine3.20"
                docker pull -q "nginxinc/nginx-unprivileged:1.27.3-alpine3.20"
                echo "Tagging nginxinc/nginx-unprivileged:1.27.3-alpine3.20 as ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"
                docker tag nginxinc/nginx-unprivileged:1.27.3-alpine3.20 ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20
                echo "Pushing ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"
                docker push -q "ghcr.io/dfe-digital/teacher-services-cloud:nginx-unprivileged-1.27.3-alpine3.20"

          - name: fail step
            run: false

          - name: SendToLogit - Workflow Completed
            shell: bash
            env:
              STEP_NAME: "WorkflowCompleted"
              LOGIT-API-KEY: ${{secrets.LOGIT_API_KEY}}
            run: |
              curl -i  \
                 -H "ApiKey: ${{ secrets.LOGIT_API_KEY }}" \
                 -H "Content-Type: application/json" \
                 -H "LogType: custom" \
                https://api-uk1.logit.io/v2 \
                -d @payload_base.json

